server:
  port: 443
  ssl:
    key-store: /Users/xiaomingcong/workspace/apache-tomcat-8.5.56-cas/conf/localhost-rsa2.jks
    key-store-password: 123456
    key-store-type: PKCS12
    keyAlias: client
condition:
  http2https: true
http:
  port: 8888
